### ISSUE TITLE
How to install the PS3EYEDriver

### ISSUE THREAD

**Issue by guvitorino** [inspirit/PS3EYEDriver#15]
I need help for install, I use windows 7.

**Comment by cboulay** [comment]
PS3EYEDriver isn't so much a driver that needs installation as it is a wrapper around libusb. See [here](https://github.com/cboulay/PSMoveService/wiki/PSEye-Software-Setup-%28Windows%29) for instructions on how to install driver for the PSEye on Windows.

Note that the PS3EYEDriver does not treat the PSEye as though it's a regular USB camera. For example, it doesn't appear in the list of supported cameras when trying to use it for video chatting. What it does do is enable raw access to the PSEye within your custom program. See [psmoveapi](https://github.com/cboulay/psmoveapi) or [PSMoveService](https://github.com/cboulay/PSMoveService) for example.

**Comment by guvitorino** [comment]
Thanks for response, that was what I needed.

**Comment by rootux** [comment]
This helped me so much. please add the link to your main README.md file.
thanks

**Comment by BenjiBearBBF** [comment]
iPi have a free driver that works with tracking PS Move. It does not work with Skype etc.
